# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Trata iOS"

  before_all do
    #
    # This will retrofit any existing schemes in fastlane/ionic/config/ios/ui-tests/
    #
    sh("cp ../../pocket-church.entitlements ./${nomeAplicativo.igreja}")
    require("/.configure_entitlements.rb")
  end

  lane :build_ios do
    # add actions here: https://docs.fastlane.tools/actions

    get_certificates
    get_provisioning_profile

    enable_automatic_code_signing(path: "${nomeAplicativo.igreja}.xcodeproj")
    gym(scheme: "${nomeAplicativo.igreja}", xcargs: "-allowProvisioningUpdates", export_method: "app-store")

    upload_to_testflight
  end
end
