# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Trata iOS"

  before_all do
    #
    # This will retrofit any existing schemes in fastlane/ionic/config/ios/ui-tests/
    #
    sh("cp ./pocket-church.entitlements/* ./platforms/ios")
    configure_entitlements

    ionic_ios_snapshot(
    	team_id: "${apple.team.id}"
    	bundle_id: "${pacote.app}"
    )
  end

  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions

    snapshot(
          output_simulator_logs: true,
          reinstall_app: false,
          erase_simulator: true,
          scheme: "Screenshots" # The name of a scheme to use, one that you generated with ionic_ios_config_snapshot
        )
  end
end
