# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Trata iOS"

  lane :beta do
    # add actions here: https://docs.fastlane.tools/actions

    get_certificates
    get_provisioning_profile

    enable_automatic_code_signing(path: "Runner.xcodeproj")
    gym(xcargs: "-allowProvisioningUpdates", export_method: "app-store")

    upload_to_testflight(
        skip_waiting_for_build_processing: true
    )
  end

  lane :release do
    deliver(
      skip_app_version_update: false, # Create the new version
      force: true,
      skip_screenshots: true,
      skip_binary_upload: true
    )
  end
end

