# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :beta do
    # add actions here: https://docs.fastlane.tools/actions

    upload_to_play_store(track: 'beta', aab: '../build/app/outputs/bundle/release/app.aab')
  end

  lane :release do
    upload_to_play_store(
      track: 'beta',
      skip_upload_apk: true,
      track_promote_to: 'production'
    )
  end
end

